# Generated by Django 4.1.7 on 2023-05-01 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="liabilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liabilityName", models.CharField(max_length=50)),
                (
                    "liabilityAmount",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("liabilityDate", models.DateField(default=django.utils.timezone.now)),
                ("liabilityTo", models.CharField(max_length=50)),
                ("liabilityStatus", models.BooleanField(default=True)),
            ],
        ),
    ]
