# Generated by Django 4.2 on 2023-04-19 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="regularmonthlyexpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expenseName", models.CharField(max_length=50)),
                ("expenseAmount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("expenseDate", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="regularmonthlyincome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incomeName", models.CharField(max_length=50)),
                ("incomeAmount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("incomeDate", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="unexpectedmonthlyexpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expenseName", models.CharField(max_length=50)),
                ("expenseAmount", models.DecimalField(decimal_places=2, max_digits=6)),
                ("expenseDate", models.DateField(default=django.utils.timezone.now)),
                ("expenseOwesTo", models.CharField(max_length=50)),
            ],
        ),
    ]
