# Generated by Django 4.1.7 on 2023-04-26 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="monthlyinvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investmentName", models.CharField(max_length=50)),
                (
                    "investmentAmount",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("investmentDate", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
