# Generated by Django 4.1.7 on 2023-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investmentmanager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyinvestment",
            name="investmentConverted",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthlyinvestment",
            name="investmentCurrency",
            field=models.CharField(default="USD", max_length=5),
            preserve_default=False,
        ),
    ]
